### PR TITLE
Update main menu icon

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Change main menu to burger icon + change it to back button on setting subpages.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by orhoj** [comment]
The icons themselves are too low quality, they don't look close to what is in Figma.

**Comment by shjortConcordium** [comment]
> The icons themselves are too low quality, they don't look close to what is in Figma.

I've tried my very best to improve this.

**Comment by orhoj** [comment]
They are still not good 😢

**Comment by shjortConcordium** [comment]
> They are still not good cry

I tried.

**Comment by orhoj** [comment]
It still looks quite janky on my homescreen, and the selected version is still not close to what I see in Figma, but I guess you talked to Jens about that?

**Comment by orhoj** [comment]
I think the icon is a bit small now, but it looks okay now. It still renders inconsistently across the 3 lines on my screen. If I zoom, then they render as the same, so I don't think the rest is fixable.

**Pull request merged**
