### PR TITLE
CI: Include hash of package.json in cache key

### PR DESCRIPTION
**Pull request by bisgardo**
## Purpose

Ensure that changes in library functions that didn't involve dependency changes invalidate the CI's dependency cache.

## Changes

Include hash of `package.json` in the cache key.

Also included a dummy value for force invalidating the cache and parameterize node version.

### CODE REVIEW

**Comment by bisgardo** [comment]
@DOBEN the problem is that the wallet API changed in https://github.com/Concordium/concordium-browser-wallet/commit/f3a5e871b53725c46fe4112b91f59e2786e0feb8 without a version bump. So because your project references the same version of the API as the one specified in the repo, it will use that instead of downloading the published package.

The easiest solution is to migrate to the new type.

I don't know how to avoid this in the future. @shjortConcordium any thoughts? I guess it comes down to what "version" means in between releases.

**Review by DOBEN — APPROVED** [review]

**Comment by shjortConcordium** [comment]
> I don't know how to avoid this in the future. @shjortConcordium any thoughts? I guess it comes down to what "version" means in between releases.

One thing would be to bump the api version when doing changes, but I think the correct thing would be to move all these examples into a separate repository. (Which also makes sense now that they no longer only used with the browser wallet)

**Comment by abizjak** [comment]
> > I don't know how to avoid this in the future. @shjortConcordium any thoughts? I guess it comes down to what "version" means in between releases.
> 
> One thing would be to bump the api version when doing changes, but I think the correct thing would be to move all these examples into a separate repository. (Which also makes sense now that they no longer only used with the browser wallet)

There are external links to the examples already, from developer documentation, and also we have given them out to various people. So please don't move stuff without addressing this issue.

**Comment by shjortConcordium** [comment]
> > > I don't know how to avoid this in the future. @shjortConcordium any thoughts? I guess it comes down to what "version" means in between releases.
> > 
> > 
> > One thing would be to bump the api version when doing changes, but I think the correct thing would be to move all these examples into a separate repository. (Which also makes sense now that they no longer only used with the browser wallet)
> 
> There are external links to the examples already, from developer documentation, and also we have given them out to various people. So please don't move stuff without addressing this issue.

I'm not saying to rush moving them, but I do think they should be moved. But when we would do it, I would update the documentation and leave the examples here as readme's with links to the new location, to avoid the broken links.
It might not be relevant here though, because it's just that the api version should be bumped/the examples should be updated to work with the changes.

**Pull request merged**
